development:
  adapter: postgresql
  encoding: unicode
  database: solvingbooks_development
  pool: 5
  username: rahm
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: solvingbooks_test
  pool: 5
  username: rahm
  password: 
